### ISSUE TITLE
Unable to connect to network server - seems like a parsing problem

### ISSUE THREAD

**Issue by timc3** [dersphere/XBMC-CouchPotato-Manager#6]
Logs look like:

```
09:23:00 T:139934807103296   DEBUG:   ParentPath = [plugin://plugin.video.couchpotato_manager/?content_type=video]
09:23:00 T:139933624809216  NOTICE: Thread JobWorker start, auto delete: true
09:23:00 T:139933624809216   DEBUG: StartScript - calling plugin CouchPotato Manager('plugin://plugin.video.couchpotato_manager/movies/status/active/','43','')
09:23:00 T:139933624809216   DEBUG: WaitOnScriptResult - waiting on the CouchPotato Manager (id=63) plugin...
09:23:00 T:139933507380992  NOTICE: Thread LanguageInvoker start, auto delete: false
09:23:00 T:139933507380992    INFO: initializing python engine.
09:23:00 T:139933507380992   DEBUG: CPythonInvoker(63, /storage/.xbmc/addons/plugin.video.couchpotato_manager/addon.py): start processing
09:23:00 T:139933507380992  NOTICE: -->Python Interpreter Initialized<--
09:23:00 T:139933507380992   DEBUG: CPythonInvoker(63, /storage/.xbmc/addons/plugin.video.couchpotato_manager/addon.py): the source file to load is /storage/.xbmc/addons/plugin.video.couchpotato_manager/addon.py
09:23:00 T:139933507380992   DEBUG: CPythonInvoker(63, /storage/.xbmc/addons/plugin.video.couchpotato_manager/addon.py): setting the Python path to /storage/.xbmc/addons/plugin.video.couchpotato_manager:/storage/.xbmc/addons/script.module.simplejson/lib:/usr/share/xbmc/addons/script.module.pil/lib:/storage/.xbmc/addons/script.common.plugin.cache/lib:/usr/share/xbmc/addons/xbmc.debug/:/storage/.xbmc/addons/script.module.beautifulsoup/lib:/storage/.xbmc/addons/script.module.parsedom/lib:/storage/.xbmc/addons/script.module.simple.downloader/lib:/storage/.xbmc/addons/script.module.xbmcswift2/lib:/usr/lib/python27.zip:/usr/lib/python2.7:/usr/lib/python2.7/plat-linux2:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/lib/python2.7/site-packages:/usr/lib/python2.7/site-packages/PIL:/usr/lib/python2.7/site-packages/gtk-2.0
09:23:00 T:139933507380992   DEBUG: CPythonInvoker(63, /storage/.xbmc/addons/plugin.video.couchpotato_manager/addon.py): entering source directory /storage/.xbmc/addons/plugin.video.couchpotato_manager
09:23:00 T:139933507380992   DEBUG: CPythonInvoker(63, /storage/.xbmc/addons/plugin.video.couchpotato_manager/addon.py): instantiating addon using automatically obtained id of "plugin.video.couchpotato_manager" dependent on version 2.1.0 of the xbmc.python api
09:23:00 T:139933507380992   DEBUG: [xbmcswift2] Reading pickle storage from disk at "/storage/.xbmc/userdata/addon_data/plugin.video.couchpotato_manager/.storage/.functions"
09:23:00 T:139933507380992   DEBUG: [xbmcswift2] Loaded storage ".functions" from disk
09:23:00 T:139933507380992   DEBUG: [xbmcswift2] Adding url rule "/" named "show_root_menu" pointing to function "show_root_menu"
09:23:00 T:139933507380992   DEBUG: [xbmcswift2] Adding url rule "/status_list/" named "show_status_list" pointing to function "show_status_list"
09:23:00 T:139933507380992   DEBUG: [xbmcswift2] Adding url rule "/movies/status/<status>/" named "show_movies" pointing to function "show_movies"
09:23:00 T:139933507380992   DEBUG: [xbmcswift2] Adding url rule "/movies/" named "show_all_movies" pointing to function "show_movies"
09:23:00 T:139933507380992   DEBUG: [xbmcswift2] Adding url rule "/movies/add/" named "add_new_wanted" pointing to function "add_new_wanted"
09:23:00 T:139933507380992   DEBUG: [xbmcswift2] Adding url rule "/movies/add-by-id/<imdb_id>" named "add_new_wanted_by_id" pointing to function "add_new_wanted_by_id"
09:23:00 T:139933507380992   DEBUG: [xbmcswift2] Adding url rule "/movies/<library_id>/releases/" named "show_releases" pointing to function "show_releases"
09:23:00 T:139933507380992   DEBUG: [xbmcswift2] Adding url rule "/movies/all/refresh" named "do_full_refresh" pointing to function "do_full_refresh"
09:23:00 T:139933507380992   DEBUG: [xbmcswift2] Adding url rule "/movies/<library_id>/refresh" named "refresh_releases" pointing to function "refresh_releases"
09:23:00 T:139933507380992   DEBUG: [xbmcswift2] Adding url rule "/movies/<library_id>/delete" named "delete_movie" pointing to function "delete_movie"
09:23:00 T:139933507380992   DEBUG: [xbmcswift2] Adding url rule "/release/<release_id>/delete" named "delete_release" pointing to function "delete_release"
09:23:00 T:139933507380992   DEBUG: [xbmcswift2] Adding url rule "/release/<release_id>/download" named "download_release" pointing to function "download_release"
09:23:00 T:139933507380992   DEBUG: [xbmcswift2] Adding url rule "/release/<release_id>/ignore" named "ignore_release" pointing to function "ignore_release"
09:23:00 T:139933507380992   DEBUG: [xbmcswift2] Adding url rule "/release/help" named "show_release_help" pointing to function "show_release_help"
09:23:00 T:139933507380992   DEBUG: [xbmcswift2] Adding url rule "/settings/default_profile" named "set_default_profile" pointing to function "set_default_profile"
09:23:00 T:139933507380992   DEBUG: [xbmcswift2] Adding url rule "/settings" named "open_settings" pointing to function "open_settings"
09:23:00 T:139933507380992  NOTICE: [CouchPotatoApi]: u'connect: hostname="luigi.narnia.lan" port="5050" use_https="False" username="" api_key="True" url_base=""'
09:23:00 T:139933507380992  NOTICE: [CouchPotatoApi]: 'trying api_key...'
09:23:00 T:139933507380992  NOTICE: [CouchPotatoApi]: '_api_call started with endpoint=app.available, params=None'
09:23:00 T:139933507380992  NOTICE: [CouchPotatoApi]: 'trying api_key: success'
09:23:00 T:139933507380992   DEBUG: [xbmcswift2] Handling incoming request for /movies/status/active/
09:23:00 T:139933507380992  NOTICE: [xbmcswift2] Request for "/movies/status/active/" matches rule for function "show_movies"
09:23:00 T:139933507380992   DEBUG: [xbmcswift2] Reading pickle storage from disk at "/storage/.xbmc/userdata/addon_data/plugin.video.couchpotato_manager/.storage/releases"
09:23:00 T:139933507380992   DEBUG: [xbmcswift2] Loaded storage "releases" from disk
09:23:00 T:139933507380992   DEBUG: [xbmcswift2] Storage hit for function "get_status_list" with args "()" and kwargs "{}"
09:23:00 T:139933507380992  NOTICE: [CouchPotatoApi]: "_api_call started with endpoint=movie.list, params={'status': 'active'}"
09:23:00 T:139933507380992   DEBUG: POParser: loaded 49 strings from file /storage/.xbmc/addons/plugin.video.couchpotato_manager/resources/language/English/strings.po
09:23:00 T:139933507380992   ERROR: EXCEPTION: Failed to convert to input type to either a std::string or a std::vector<(XBMCAddon::xbmcgui::InfoLabelStringOrTuple)>
09:23:00 T:139933507380992   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: Failed to convert to input type to either a std::string or a std::vector<(XBMCAddon::xbmcgui::InfoLabelStringOrTuple)>
                                            Traceback (most recent call last):
                                              File "/storage/.xbmc/addons/plugin.video.couchpotato_manager/addon.py", line 504, in <module>
                                                plugin.run()
                                              File "/storage/.xbmc/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 332, in run
                                                items = self._dispatch(self.request.path)
                                              File "/storage/.xbmc/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 306, in _dispatch
                                                listitems = view_func(**items)
                                              File "/storage/.xbmc/addons/plugin.video.couchpotato_manager/addon.py", line 237, in show_movies
                                                return plugin.finish(items, sort_methods=sort_methods)
                                              File "/storage/.xbmc/addons/script.module.xbmcswift2/lib/xbmcswift2/xbmcmixin.py", line 493, in finish
                                                self.add_items(items)
                                              File "/storage/.xbmc/addons/script.module.xbmcswift2/lib/xbmcswift2/xbmcmixin.py", line 409, in add_items
                                                _items = [self._listitemify(item) for item in items]
                                              File "/storage/.xbmc/addons/script.module.xbmcswift2/lib/xbmcswift2/xbmcmixin.py", line 314, in _listitemify
                                                item = xbmcswift2.ListItem.from_dict(**item)
                                              File "/storage/.xbmc/addons/script.module.xbmcswift2/lib/xbmcswift2/listitem.py", line 201, in from_dict
                                                listitem.set_info(info_type, info)
                                              File "/storage/.xbmc/addons/script.module.xbmcswift2/lib/xbmcswift2/listitem.py", line 101, in set_info
                                                return self._listitem.setInfo(type, info_labels)
                                            TypeError: Failed to convert to input type to either a std::string or a std::vector<(XBMCAddon::xbmcgui::InfoLabelStringOrTuple)>
                                            -->End of Python script error report<--
```

This is on XBMC Gotham.

**Comment by dersphere** [comment]
Please tell me your exact XBMC Gotham Version number (or the GIT Commit ID).
This is a bug in XBMC.

**Comment by timc3** [comment]
OpenELEC (unofficial) Version: devel-20131230133454-r16750-gd434c0e
OpenELEC git: d434c0e692f9859a9d0f05051a028163dbc847ab

Which contains:

XBMC Media Center 13.0-ALPHA11 Git:a9e8763

( reported by /usr/lib/xbmc/xbmc.bin --version )

**Comment by dersphere** [comment]
Thanks.
This error only occurs in nightly builds and should be fixed by XBMC.
(FYI Commit https://github.com/xbmc/xbmc/commit/820aa4df2dded16e1a9e8e5061f7080adf6c1cb0 may also raise errors in other plugins)

**Comment by timc3** [comment]
Ok thanks for letting me know.
